# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: hola-mundo
run-name: Estoy aprendiendo GitHub Actions
on: [push]
jobs:
  print-hello-world:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name:  Run script
      run: swift test.swift

